/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace WatchVault {
  export type WatchStruct = {
    id: BigNumberish;
    brand: string;
    model: string;
    year: BigNumberish;
    description: string;
    imageUrl: string;
    purchasePrice: BigNumberish;
    totalShares: BigNumberish;
    sharesSold: BigNumberish;
    sold: boolean;
    salePrice: BigNumberish;
  };

  export type WatchStructOutput = [
    id: bigint,
    brand: string,
    model: string,
    year: bigint,
    description: string,
    imageUrl: string,
    purchasePrice: bigint,
    totalShares: bigint,
    sharesSold: bigint,
    sold: boolean,
    salePrice: bigint
  ] & {
    id: bigint;
    brand: string;
    model: string;
    year: bigint;
    description: string;
    imageUrl: string;
    purchasePrice: bigint;
    totalShares: bigint;
    sharesSold: bigint;
    sold: boolean;
    salePrice: bigint;
  };
}

export interface WatchVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyShares"
      | "claimRevenue"
      | "claimableAmount"
      | "claimed"
      | "getWatch"
      | "getWatchCount"
      | "nextWatchId"
      | "owner"
      | "platformRevenueWithdrawn"
      | "registerWatch"
      | "remainingShares"
      | "renounceOwnership"
      | "sellWatch"
      | "sharePrice"
      | "shares"
      | "transferOwnership"
      | "watches"
      | "withdrawPlatformRevenue"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PlatformRevenueWithdrawn"
      | "RevenueClaimed"
      | "SharesPurchased"
      | "WatchRegistered"
      | "WatchSold"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buyShares",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRevenue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimableAmount",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimed",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWatchCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextWatchId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformRevenueWithdrawn",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerWatch",
    values: [
      string,
      string,
      BigNumberish,
      string,
      string,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "remainingShares",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sellWatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sharePrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "shares",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "watches",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPlatformRevenue",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "buyShares", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getWatch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getWatchCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextWatchId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformRevenueWithdrawn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerWatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remainingShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sellWatch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sharePrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "shares", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "watches", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPlatformRevenue",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformRevenueWithdrawnEvent {
  export type InputTuple = [watchId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [watchId: bigint, amount: bigint];
  export interface OutputObject {
    watchId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevenueClaimedEvent {
  export type InputTuple = [
    watchId: BigNumberish,
    investor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [watchId: bigint, investor: string, amount: bigint];
  export interface OutputObject {
    watchId: bigint;
    investor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesPurchasedEvent {
  export type InputTuple = [
    watchId: BigNumberish,
    investor: AddressLike,
    amount: BigNumberish,
    totalCost: BigNumberish
  ];
  export type OutputTuple = [
    watchId: bigint,
    investor: string,
    amount: bigint,
    totalCost: bigint
  ];
  export interface OutputObject {
    watchId: bigint;
    investor: string;
    amount: bigint;
    totalCost: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WatchRegisteredEvent {
  export type InputTuple = [
    watchId: BigNumberish,
    brand: string,
    model: string,
    purchasePrice: BigNumberish,
    totalShares: BigNumberish
  ];
  export type OutputTuple = [
    watchId: bigint,
    brand: string,
    model: string,
    purchasePrice: bigint,
    totalShares: bigint
  ];
  export interface OutputObject {
    watchId: bigint;
    brand: string;
    model: string;
    purchasePrice: bigint;
    totalShares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WatchSoldEvent {
  export type InputTuple = [watchId: BigNumberish, salePrice: BigNumberish];
  export type OutputTuple = [watchId: bigint, salePrice: bigint];
  export interface OutputObject {
    watchId: bigint;
    salePrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WatchVault extends BaseContract {
  connect(runner?: ContractRunner | null): WatchVault;
  waitForDeployment(): Promise<this>;

  interface: WatchVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyShares: TypedContractMethod<
    [watchId: BigNumberish, amount: BigNumberish],
    [void],
    "payable"
  >;

  claimRevenue: TypedContractMethod<
    [watchId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimableAmount: TypedContractMethod<
    [watchId: BigNumberish, investor: AddressLike],
    [bigint],
    "view"
  >;

  claimed: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  getWatch: TypedContractMethod<
    [watchId: BigNumberish],
    [WatchVault.WatchStructOutput],
    "view"
  >;

  getWatchCount: TypedContractMethod<[], [bigint], "view">;

  nextWatchId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  platformRevenueWithdrawn: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  registerWatch: TypedContractMethod<
    [
      brand: string,
      model: string,
      year: BigNumberish,
      description: string,
      imageUrl: string,
      purchasePrice: BigNumberish,
      totalShares: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  remainingShares: TypedContractMethod<
    [watchId: BigNumberish],
    [bigint],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sellWatch: TypedContractMethod<[watchId: BigNumberish], [void], "payable">;

  sharePrice: TypedContractMethod<[watchId: BigNumberish], [bigint], "view">;

  shares: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  watches: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        id: bigint;
        brand: string;
        model: string;
        year: bigint;
        description: string;
        imageUrl: string;
        purchasePrice: bigint;
        totalShares: bigint;
        sharesSold: bigint;
        sold: boolean;
        salePrice: bigint;
      }
    ],
    "view"
  >;

  withdrawPlatformRevenue: TypedContractMethod<
    [watchId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyShares"
  ): TypedContractMethod<
    [watchId: BigNumberish, amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "claimRevenue"
  ): TypedContractMethod<[watchId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimableAmount"
  ): TypedContractMethod<
    [watchId: BigNumberish, investor: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimed"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWatch"
  ): TypedContractMethod<
    [watchId: BigNumberish],
    [WatchVault.WatchStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWatchCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextWatchId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformRevenueWithdrawn"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerWatch"
  ): TypedContractMethod<
    [
      brand: string,
      model: string,
      year: BigNumberish,
      description: string,
      imageUrl: string,
      purchasePrice: BigNumberish,
      totalShares: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "remainingShares"
  ): TypedContractMethod<[watchId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sellWatch"
  ): TypedContractMethod<[watchId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "sharePrice"
  ): TypedContractMethod<[watchId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "shares"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "watches"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        id: bigint;
        brand: string;
        model: string;
        year: bigint;
        description: string;
        imageUrl: string;
        purchasePrice: bigint;
        totalShares: bigint;
        sharesSold: bigint;
        sold: boolean;
        salePrice: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawPlatformRevenue"
  ): TypedContractMethod<[watchId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PlatformRevenueWithdrawn"
  ): TypedContractEvent<
    PlatformRevenueWithdrawnEvent.InputTuple,
    PlatformRevenueWithdrawnEvent.OutputTuple,
    PlatformRevenueWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "RevenueClaimed"
  ): TypedContractEvent<
    RevenueClaimedEvent.InputTuple,
    RevenueClaimedEvent.OutputTuple,
    RevenueClaimedEvent.OutputObject
  >;
  getEvent(
    key: "SharesPurchased"
  ): TypedContractEvent<
    SharesPurchasedEvent.InputTuple,
    SharesPurchasedEvent.OutputTuple,
    SharesPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "WatchRegistered"
  ): TypedContractEvent<
    WatchRegisteredEvent.InputTuple,
    WatchRegisteredEvent.OutputTuple,
    WatchRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "WatchSold"
  ): TypedContractEvent<
    WatchSoldEvent.InputTuple,
    WatchSoldEvent.OutputTuple,
    WatchSoldEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PlatformRevenueWithdrawn(uint256,uint256)": TypedContractEvent<
      PlatformRevenueWithdrawnEvent.InputTuple,
      PlatformRevenueWithdrawnEvent.OutputTuple,
      PlatformRevenueWithdrawnEvent.OutputObject
    >;
    PlatformRevenueWithdrawn: TypedContractEvent<
      PlatformRevenueWithdrawnEvent.InputTuple,
      PlatformRevenueWithdrawnEvent.OutputTuple,
      PlatformRevenueWithdrawnEvent.OutputObject
    >;

    "RevenueClaimed(uint256,address,uint256)": TypedContractEvent<
      RevenueClaimedEvent.InputTuple,
      RevenueClaimedEvent.OutputTuple,
      RevenueClaimedEvent.OutputObject
    >;
    RevenueClaimed: TypedContractEvent<
      RevenueClaimedEvent.InputTuple,
      RevenueClaimedEvent.OutputTuple,
      RevenueClaimedEvent.OutputObject
    >;

    "SharesPurchased(uint256,address,uint256,uint256)": TypedContractEvent<
      SharesPurchasedEvent.InputTuple,
      SharesPurchasedEvent.OutputTuple,
      SharesPurchasedEvent.OutputObject
    >;
    SharesPurchased: TypedContractEvent<
      SharesPurchasedEvent.InputTuple,
      SharesPurchasedEvent.OutputTuple,
      SharesPurchasedEvent.OutputObject
    >;

    "WatchRegistered(uint256,string,string,uint256,uint256)": TypedContractEvent<
      WatchRegisteredEvent.InputTuple,
      WatchRegisteredEvent.OutputTuple,
      WatchRegisteredEvent.OutputObject
    >;
    WatchRegistered: TypedContractEvent<
      WatchRegisteredEvent.InputTuple,
      WatchRegisteredEvent.OutputTuple,
      WatchRegisteredEvent.OutputObject
    >;

    "WatchSold(uint256,uint256)": TypedContractEvent<
      WatchSoldEvent.InputTuple,
      WatchSoldEvent.OutputTuple,
      WatchSoldEvent.OutputObject
    >;
    WatchSold: TypedContractEvent<
      WatchSoldEvent.InputTuple,
      WatchSoldEvent.OutputTuple,
      WatchSoldEvent.OutputObject
    >;
  };
}
